# Generated by Django 4.2.7 on 2024-07-28 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='DancerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='DanceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('grade', models.FloatField()),
                ('end_photo', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='dancerimage',
            name='dance_sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dancesequence'),
        ),
        migrations.AddField(
            model_name='customerimage',
            name='dance_sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dancesequence'),
        ),
    ]
