# Generated by Django 4.2.7 on 2024-07-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customerimage_dancerimage_dancesequence_delete_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dancer_image', models.ImageField(upload_to='media/')),
                ('customer_image', models.TextField()),
                ('dance_sequence', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='dancerimage',
            name='dance_sequence',
        ),
        migrations.DeleteModel(
            name='CustomerImage',
        ),
        migrations.DeleteModel(
            name='DancerImage',
        ),
    ]
