# Generated by Django 4.2.7 on 2024-07-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_imagesnapshot_dance_sequence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesnapshot',
            name='feedback',
            field=models.TextField(default='-', max_length=755),
        ),
        migrations.AddField(
            model_name='imagesnapshot',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
